apiVersion: v1
kind: Service
metadata:
  name: zeppelinq
  labels:
    app: zeppelinq
spec:
  ports:
  - name: zepp
    port: 8080
  - name: jpty
    port: 8888
  selector:
    app: zeppelinq
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: zeppelinq
  labels:
    app: zeppelinq

spec:
  revisionHistoryLimit: 0
  strategy:
    # type: RollingUpdate
    type: Recreate

  selector:
    matchLabels:
      app: zeppelinq

  template:
    metadata:
      labels:
        app: zeppelinq

    spec:
      #Actual Mounting Path on k8s-node
      volumes:
        - name: zeppelinq-conf
          hostPath:
            path: /opt/appdata/zeppelinq/conf
            type: Directory
        - name: zeppelinq-notebooks
          hostPath:
            path: /opt/appdata/zeppelinq/notebook
            type: Directory
        - name: zeppelinq-pyenvs
          hostPath:
            path: /opt/appdata/zeppelinq/opt/pyenvs
            type: Directory
        - name: zeppelinq-pymodules
          hostPath:
            path: /opt/appdata/zeppelinq/opt/pymodules
            type: Directory

      # Container
      containers:
      - image: registry.qraftec.cloud/zeppelinq:0.1.1-beta
        name: zeppelinq
        imagePullPolicy: IfNotPresent
        # Mounting volume
        volumeMounts:
        - name: zeppelinq-conf
          mountPath: /zeppelin/conf
        - name: zeppelinq-notebooks
          mountPath: /zeppelin/notebook
        - name: zeppelinq-pyenvs
          mountPath: /opt/pyenvs
        - name: zeppelinq-pymodules
          mountPath: /opt/pymodules
        # Exposing port
        ports:
          - containerPort: 8080
            name: port-zepp
          - containerPort: 8080
            name: port-jpty

      imagePullSecrets:
        - name: regcred

      restartPolicy: Always